### ISSUE TITLE
4.12 esri js replacement changes

### ISSUE THREAD

**Issue by steveoh** [agrc-widgets/kitchen-sink#12]
**Describe the bug**

Using esri 4.12 js api, requests to discover contain dollar signs `$`.

**Expected behavior**

url should not contain `$`.

**Additional context**

The replacing function was reimplemented for intl. Dojo was probably handling the `${var}` replacement but esri only expects `{var}` now. 

Update the layer selector to use the backward compatible `{var}` style.

**Comment by stdavis** [comment]
I believe that this is fixed now: https://github.com/agrc-widgets/kitchen-sink/blob/9a08db1f1ccb3fca23db73e285e97b8d8d7071d9/packages/layer-selector/LayerSelector.js#L206
