### ISSUE TITLE
.npmignore

### ISSUE THREAD

**Issue by stdavis** [agrc-widgets/kitchen-sink#2]
I wonder if there's a way that we can hoist the .npmignore file and keep only package-specific entries in the packages.

**Comment by steveoh** [comment]
It could be a grunt task? or a prepublish script? I'm not sure. I don't see an issue managing it at the top level.

**Comment by steveoh** [comment]
i've been reading it is better to whitelist instead of black list. Let's not use `.npmignore` files at all.
