### ISSUE TITLE
Automated change log and version number management

### ISSUE THREAD

**Issue by stdavis** [agrc-widgets/kitchen-sink#30]
It would be nice to automate a changelog and version bump via standard release or something like that. I'm guessing that we would need to standardize our conventional commit scopes.

**Comment by steveoh** [comment]
pretty sure this is already implemented in lerna

**Comment by stdavis** [comment]
Yes, I was just noticing that nice changelog. I've not been using cc scopes. Maybe once #29 is merged, I can reword the commits on master.
